Add /namecolors command
Veraticus/clearingway pull request #26
Opened 2024-07-25 06:22 UTC by OTCompa

Requested by @clairefleuret
Adds a command to give the invoker the respective name color role as configured in `config.yaml`. Only one name color role will be applied at a given time and will remove any other name color roles already present on the user. Can be used again to toggle off the role.

## config.yaml
Based on what's already in `encounters.go`.
To enable the command in a guild: `nameColor` must be set to `true` in the guild's config.
Role `type` should be `Name Color`
Here's a sample `config.yaml` which should work for the examples below.
```yaml
guilds:
- name: NAUR
  roles:
    nameColor: true
  guildId: 1234567890
  channelId: 1234567890
  encounters:
  - ids: [1060, 1047, 1039, 1073]
    name: "The Unending Coil of Bahamut (Ultimate)"
    defaultRoles: false
    totalWeaponsAvailable: 15
    the: "Legendary"
    roles:
      - name: "UCoB Cleared"
        type: "Cleared"
        color: 0xfdfd96
      - name: "The Legend's Color"
        type: "Name Color"
        color: 0xfdfd96
```
A separate PR will be made to modify `config.yaml` so that the commands will be set up for NAUR.
## Examples:
(Ignore the bot name I just reused the same token lol)
![image](https://github.com/user-attachments/assets/880f35f3-45db-4528-833e-2838595a5940)

If prerequisite role is not present:
![image](https://github.com/user-attachments/assets/d9b958c9-038c-43cd-901d-596c2b26521d)

If prerequisite role is present and no other name color role is present:
![image](https://github.com/user-attachments/assets/2678a3f4-767a-4a44-9342-e6f0252c8ee9)

If prerequisite role is present and another name color role is present:
![image](https://github.com/user-attachments/assets/c55870b9-23ee-4ba0-b3c8-0bfc7c87df09)

If the same name color role is present (toggle role):
![image](https://github.com/user-attachments/assets/3d2cfc6b-5bf4-4844-8394-40a72710c400)

2024-07-25 12:30 UTC, clairefleuret commented
All use cases have been tested, no issues found.

2024-07-25 12:36 UTC, clairefleuret commented on internal/clearingway/handlers.go
> +					Name: "FRU",
Prepared for FRU release, can be uncommented when the fight goes live.

2024-07-25 23:51 UTC, brtran4 requested changes

2024-07-25 23:51 UTC, brtran4 commented on internal/clearingway/handlers.go
> +	}
just like the first PR, let's add an ephemeral message to the user to use it in the correct channel

2024-07-25 23:51 UTC, brtran4 commented on internal/clearingway/handlers.go
> +		}
i'm kind of surprised that there's no helper function to being with. let's make this a helper

2024-07-25 23:51 UTC, brtran4 commented on internal/clearingway/handlers.go
> +			tempstr += fmt.Sprintf("\nSuccessfully added role: <@&%v>", requestedColorRole.DiscordRole.ID)
this also goes with making this a helper as well. we might as well replace all current implementations of adding a role with this helper in a separate PR. but, for now let's separate this into a helper and replace only this piece of code with the helper (and other places you've written similar code)

2024-07-25 23:51 UTC, brtran4 commented on internal/clearingway/handlers.go
> +			discord.ContinueInteraction(s, i.Interaction, tempstr)
same concept here

2024-07-27 01:36 UTC, brtran4 approved these changes

2024-07-27 02:20 UTC, merged